const toWatch = [
  "https://myanimelist.net/anime/5630/Higashi_no_Eden",
  "https://myanimelist.net/anime/9253/Steins_Gate",
  "https://myanimelist.net/anime/30276/One_Punch_Man",
  "https://myanimelist.net/anime/27899/Tokyo_Ghoul_%E2%88%9AA",
  "https://myanimelist.net/anime/790/Ergo_Proxy",
  "https://myanimelist.net/anime/11111/Another",
  "https://myanimelist.net/anime/12431/Uchuu_Kyoudai",
  "https://myanimelist.net/anime/6746/Durarara",
  "https://myanimelist.net/anime/28977/Gintama%C2%B0",
  "https://myanimelist.net/anime/3002/Gyakkyou_Burai_Kaiji__Ultimate_Survivor",
  "https://myanimelist.net/anime/32379/Berserk",
  "https://myanimelist.net/anime/934/Higurashi_no_Naku_Koro_ni",
  "https://myanimelist.net/anime/13125/Shinsekai_yori",
  "https://myanimelist.net/anime/9756/Mahou_Shoujo_Madoka★Magica",
  "https://myanimelist.net/anime/4382/Suzumiya_Haruhi_no_Yuuutsu_2009",
  "https://myanimelist.net/anime/31478/Bungou_Stray_Dogs",
  "https://myanimelist.net/anime/13601/Psycho-Pass",
  "https://myanimelist.net/anime/23283/Zankyou_no_Terror",
  "https://myanimelist.net/anime/2251/Baccano",
  "https://myanimelist.net/anime/31646/3-gatsu_no_Lion",
  "https://myanimelist.net/anime/339/Serial_Experiments_Lain",
  "https://myanimelist.net/anime/29803/Overlord",
  "https://myanimelist.net/anime/384/Gantz",
  "https://myanimelist.net/anime/10087/Fate_Zero",
  "https://myanimelist.net/anime/11741/Fate_Zero_2nd_Season",
  "https://myanimelist.net/anime/323/Mousou_Dairinin",
  "https://myanimelist.net/anime/26/Texhnolyze",
  "https://myanimelist.net/anime/22199/Akame_ga_Kill",
  "https://myanimelist.net/anime/6114/Rainbow__Nisha_Rokubou_no_Shichinin",
  "https://myanimelist.net/anime/32182/Mob_Psycho_100",
  "https://myanimelist.net/anime/1/Cowboy_Bebop"
];

module.exports = toWatch;
